"""Add game engine models

Revision ID: 5e95b9762fd1
Revises: 88d8c1bd8ef3
Create Date: 2025-11-15 21:10:52.124571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e95b9762fd1'
down_revision = '88d8c1bd8ef3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.String(length=50), nullable=False),
    sa.Column('from_position', sa.Integer(), nullable=False),
    sa.Column('to_position', sa.Integer(), nullable=False),
    sa.Column('dice_value', sa.Integer(), nullable=False),
    sa.Column('move_type', sa.String(length=20), nullable=False),
    sa.Column('captured_piece_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_moves_game_id'), 'game_moves', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_moves_player_id'), 'game_moves', ['player_id'], unique=False)
    op.drop_index('ix_game_states_game_id', table_name='game_states')
    op.drop_index('ix_game_states_turn_number', table_name='game_states')
    op.drop_table('game_states')
    op.drop_index('ix_moves_game_id', table_name='moves')
    op.drop_index('ix_moves_player_id', table_name='moves')
    op.drop_index('ix_moves_turn_number', table_name='moves')
    op.drop_table('moves')
    op.add_column('game_players', sa.Column('color', sa.String(length=20), nullable=False))
    op.drop_column('game_players', 'join_order')
    op.drop_column('game_players', 'turn_order')
    op.drop_column('game_players', 'final_position')
    op.drop_column('game_players', 'player_position')
    op.drop_column('game_players', 'player_color')
    op.drop_column('game_players', 'is_bot')
    op.add_column('games', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('games', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('games', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('games', sa.Column('created_by', sa.UUID(), nullable=False))
    op.drop_index('ix_games_game_code', table_name='games')
    op.create_foreign_key(None, 'games', 'users', ['created_by'], ['id'])
    op.drop_column('games', 'current_players')
    op.drop_column('games', 'game_code')
    op.drop_column('games', 'game_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('game_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('current_players', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_index('ix_games_game_code', 'games', ['game_code'], unique=False)
    op.drop_column('games', 'created_by')
    op.drop_column('games', 'password_hash')
    op.drop_column('games', 'is_private')
    op.drop_column('games', 'name')
    op.add_column('game_players', sa.Column('is_bot', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('game_players', sa.Column('player_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('game_players', sa.Column('player_position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('game_players', sa.Column('final_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game_players', sa.Column('turn_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('game_players', sa.Column('join_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('game_players', 'color')
    op.create_table('moves',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('turn_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('move_sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('piece_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('move_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dice_used', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('captured_pieces', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('was_recommended', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('move_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='moves_game_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], name='moves_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='moves_pkey')
    )
    op.create_index('ix_moves_turn_number', 'moves', ['turn_number'], unique=False)
    op.create_index('ix_moves_player_id', 'moves', ['player_id'], unique=False)
    op.create_index('ix_moves_game_id', 'moves', ['game_id'], unique=False)
    op.create_table('game_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('turn_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('board_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('dice_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_action', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_player_id'], ['users.id'], name='game_states_current_player_id_fkey'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_states_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_states_pkey')
    )
    op.create_index('ix_game_states_turn_number', 'game_states', ['turn_number'], unique=False)
    op.create_index('ix_game_states_game_id', 'game_states', ['game_id'], unique=False)
    op.drop_index(op.f('ix_game_moves_player_id'), table_name='game_moves')
    op.drop_index(op.f('ix_game_moves_game_id'), table_name='game_moves')
    op.drop_table('game_moves')
    # ### end Alembic commands ###