"""Initial migration - create all tables

Revision ID: 88d8c1bd8ef3
Revises: 
Create Date: 2025-11-15 20:48:38.223108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d8c1bd8ef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_bots_difficulty'), 'ai_bots', ['difficulty'], unique=False)
    op.create_index(op.f('ix_ai_bots_id'), 'ai_bots', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('current_players', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('game_settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_created_at'), 'games', ['created_at'], unique=False)
    op.create_index(op.f('ix_games_game_code'), 'games', ['game_code'], unique=True)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('preferred_color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_training_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('move_made', sa.JSON(), nullable=False),
    sa.Column('move_evaluation', sa.Float(), nullable=False),
    sa.Column('game_outcome', sa.String(length=20), nullable=False),
    sa.Column('learning_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['ai_bots.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_training_data_bot_id'), 'ai_training_data', ['bot_id'], unique=False)
    op.create_index(op.f('ix_ai_training_data_game_id'), 'ai_training_data', ['game_id'], unique=False)
    op.create_table('distributed_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('client_timestamps', sa.JSON(), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(), nullable=False),
    sa.Column('calculated_offset', sa.Integer(), nullable=False),
    sa.Column('sync_accuracy_ms', sa.Integer(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributed_sync_logs_game_id'), 'distributed_sync_logs', ['game_id'], unique=False)
    op.create_table('game_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('game_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('winner_analysis', sa.JSON(), nullable=False),
    sa.Column('player_performances', sa.JSON(), nullable=False),
    sa.Column('critical_moments', sa.JSON(), nullable=False),
    sa.Column('move_quality_scores', sa.JSON(), nullable=False),
    sa.Column('recommendation_accuracy', sa.Float(), nullable=True),
    sa.Column('ai_insights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_analyses_game_id'), 'game_analyses', ['game_id'], unique=True)
    op.create_table('game_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('player_color', sa.String(length=20), nullable=False),
    sa.Column('player_position', sa.Integer(), nullable=False),
    sa.Column('join_order', sa.Integer(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_players_game_id'), 'game_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_players_user_id'), 'game_players', ['user_id'], unique=False)
    op.create_table('game_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('current_player_id', sa.UUID(), nullable=False),
    sa.Column('board_state', sa.JSON(), nullable=False),
    sa.Column('dice_values', sa.JSON(), nullable=True),
    sa.Column('last_action', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_states_game_id'), 'game_states', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_states_turn_number'), 'game_states', ['turn_number'], unique=False)
    op.create_table('game_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('games_lost', sa.Integer(), nullable=False),
    sa.Column('games_abandoned', sa.Integer(), nullable=False),
    sa.Column('total_moves', sa.Integer(), nullable=False),
    sa.Column('total_captures', sa.Integer(), nullable=False),
    sa.Column('total_captured', sa.Integer(), nullable=False),
    sa.Column('average_game_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('favorite_color', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_statistics_user_id'), 'game_statistics', ['user_id'], unique=True)
    op.create_table('moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('move_sequence', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('from_position', sa.Integer(), nullable=False),
    sa.Column('to_position', sa.Integer(), nullable=False),
    sa.Column('move_type', sa.String(length=20), nullable=False),
    sa.Column('dice_used', sa.JSON(), nullable=False),
    sa.Column('captured_pieces', sa.JSON(), nullable=True),
    sa.Column('was_recommended', sa.Boolean(), nullable=False),
    sa.Column('move_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moves_game_id'), 'moves', ['game_id'], unique=False)
    op.create_index(op.f('ix_moves_player_id'), 'moves', ['player_id'], unique=False)
    op.create_index(op.f('ix_moves_turn_number'), 'moves', ['turn_number'], unique=False)
    op.create_table('recommendation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('recommended_moves', sa.JSON(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('player_followed', sa.Boolean(), nullable=True),
    sa.Column('actual_move', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_logs_game_id'), 'recommendation_logs', ['game_id'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_player_id'), 'recommendation_logs', ['player_id'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_turn_number'), 'recommendation_logs', ['turn_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_logs_turn_number'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_recommendation_logs_player_id'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_recommendation_logs_game_id'), table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    op.drop_index(op.f('ix_moves_turn_number'), table_name='moves')
    op.drop_index(op.f('ix_moves_player_id'), table_name='moves')
    op.drop_index(op.f('ix_moves_game_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_game_statistics_user_id'), table_name='game_statistics')
    op.drop_table('game_statistics')
    op.drop_index(op.f('ix_game_states_turn_number'), table_name='game_states')
    op.drop_index(op.f('ix_game_states_game_id'), table_name='game_states')
    op.drop_table('game_states')
    op.drop_index(op.f('ix_game_players_user_id'), table_name='game_players')
    op.drop_index(op.f('ix_game_players_game_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_game_analyses_game_id'), table_name='game_analyses')
    op.drop_table('game_analyses')
    op.drop_index(op.f('ix_distributed_sync_logs_game_id'), table_name='distributed_sync_logs')
    op.drop_table('distributed_sync_logs')
    op.drop_index(op.f('ix_ai_training_data_game_id'), table_name='ai_training_data')
    op.drop_index(op.f('ix_ai_training_data_bot_id'), table_name='ai_training_data')
    op.drop_table('ai_training_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_code'), table_name='games')
    op.drop_index(op.f('ix_games_created_at'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_ai_bots_id'), table_name='ai_bots')
    op.drop_index(op.f('ix_ai_bots_difficulty'), table_name='ai_bots')
    op.drop_table('ai_bots')
    # ### end Alembic commands ###